if (typeof GB === 'undefined' ) GB={};
GB.rules=[
    {   
        keeper:1,
        score50:2,
        score80:6,
        wall:2
    },
    {   
        keeper:1,
        score50:2,
        score80:6,
        wall:2
    },
    {   
        keeper:2,
        score50:3,
        score80:5,
        wall:3
    }
];